/******************************************************************************/
/****              Generated by IBExpert 20/10/2023 20:08:18               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE CADCLIENTE (
    ID             INTEGER NOT NULL,
    NOMEFANTASIA   VARCHAR(100),
    RAZAOSOCIAL    VARCHAR(100),
    CNPJ           VARCHAR(14),
    IE             VARCHAR(20),
    DDD            VARCHAR(2),
    TELEFONE       VARCHAR(20),
    DDD2           VARCHAR(2),
    TELEFONE2      VARCHAR(20),
    DDD_CELULAR    VARCHAR(2),
    CELULAR        VARCHAR(20),
    SITE           VARCHAR(100),
    DATA_CADASTRO  DATE,
    INATIVO        INTEGER,
    DATA_INATIVO   DATE,
    OBS            VARCHAR(2500),
    ID_EMP         INTEGER,
    IM             VARCHAR(20),
    SEXO           VARCHAR(1),
    TIPOPESSOA     VARCHAR(2)
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE CADCLIENTE ADD CONSTRAINT PK_CADCLIENTE PRIMARY KEY (ID);


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
