/******************************************************************************/
/****              Generated by IBExpert 21/10/2023 11:02:18               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_CADPRODUTO;

CREATE TABLE CADPRODUTO (
    ID             INTEGER NOT NULL,
    CODFISCAL      VARCHAR(60),
    TIPO           VARCHAR(30),
    DESCRICAO      VARCHAR(100),
    COMPLEMENTO    VARCHAR(150),
    UNIDMED        VARCHAR(6),
    VALORUNIT      NUMERIC(15,8),
    CUSTOUNIT      NUMERIC(15,8),
    LUCRO          NUMERIC(15,8),
    MARKUP         NUMERIC(15,8),
    ESTMIN         INTEGER,
    ESTMAX         INTEGER,
    PRODMIN        INTEGER,
    PESO           NUMERIC(15,4),
    NCM            VARCHAR(15),
    INFOADICIONAL  VARCHAR(1000),
    EAN            VARCHAR(14),
    INATIVO        INTEGER
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE CADPRODUTO ADD CONSTRAINT PK_CADPRODUTO PRIMARY KEY (ID);


/******************************************************************************/
/****                               Indices                                ****/
/******************************************************************************/

CREATE UNIQUE INDEX CADPRODUTO_IDX_CODFISCAL ON CADPRODUTO (CODFISCAL);
CREATE UNIQUE INDEX CADPRODUTO_IDX_DESCRICAO ON CADPRODUTO (DESCRICAO);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: TG_CADPRODUTO */
CREATE OR ALTER TRIGGER TG_CADPRODUTO FOR CADPRODUTO
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS 
 begin 
   IF (NEW.ID IS NULL) THEN NEW.ID = gen_id(gen_cadproduto,1); 
 end
^
SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
