/******************************************************************************/
/****              Generated by IBExpert 20/10/2023 20:06:49               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/


CREATE GENERATOR GEN_EMPRESA_ID;

CREATE TABLE EMPRESA (
    ID            INTEGER NOT NULL,
    NOMEFANTASIA  VARCHAR(100),
    RAZAOSOCIAL   VARCHAR(100),
    CNPJ          VARCHAR(14),
    IE            VARCHAR(20),
    IM            VARCHAR(20),
    CNAE          VARCHAR(10),
    CRT           INTEGER,
    DDD           VARCHAR(2),
    TELEFONE      VARCHAR(12),
    DDD2          VARCHAR(2),
    TELEFONE2     VARCHAR(12) CHARACTER SET NONE,
    DDD_CELULAR   VARCHAR(2),
    CELULAR       VARCHAR(12),
    SITE          VARCHAR(100),
    EMAIL         VARCHAR(100),
    CEP           VARCHAR(8),
    ENDERECO      VARCHAR(100),
    NUMERO        VARCHAR(15),
    COMPLEMENTO   VARCHAR(80),
    BAIRRO        VARCHAR(80),
    CIDADE        VARCHAR(80),
    ESTADO        VARCHAR(2),
    ID_MUNICIPIO  INTEGER
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE EMPRESA ADD CONSTRAINT "FK_EMPRESA->MUNICIPIO" FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: EMPRESA_BI */
CREATE OR ALTER TRIGGER EMPRESA_BI FOR EMPRESA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_empresa_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/
